name: Run NSE Option Chain Script

on:
  schedule:
    # Run every day at 10 PM IST, Monday to Friday
  - cron: '*/3 3-10 * * 1-5'  # This cron schedule runs every 5 minutes Monday to Friday, from 9:15 AM to 3:30 PM IST
  workflow_dispatch:  # Allows manual trigger of the workflow
   

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client pandas nsepython python-dotenv

      - name: Run script
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}  # Ensure this matches the secret's name in GitHub
        run: python nseoptionchain.py
