name: Run NSE Option Chain Script

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Specify a consistent version like 3.9

      # Cache pip dependencies to make future runs faster
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install Python dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # Set up Google Sheets credentials using GitHub Secrets
      - name: Set up Google credentials
        run: |
          echo "$GOOGLE_SHEETS_CREDENTIALS" > credentials.json
          export GOOGLE_SHEETS_CREDENTIALS=$PWD/credentials.json
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}

      # Run the Python script
      - name: Run the Python script
        run: |
          python nseoptionchain.py
