jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "${{ secrets.CREDENTIALS_JSON }}" > credentials.json

      - name: Run script
        run: python nseoptionchain.py
        env:
         GOOGLE_SHEETS_CREDENTIALS: credentials.json
